const trackTypes = {
  FETCHING: "FETCHING",
  GET_TRACKLIST_SUCCESS: "GET_TRACKLIST_SUCCESS",
  GET_TRACKLIST_ERROR: "GET_TRACKLIST_ERROR",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_ERROR: "SEARCH_ERROR"
};

export { trackTypes };
